### ISSUE TITLE
Plugin update breaks my site, "undefined variable $customDateFormat"

### ISSUE THREAD

**Issue by Japhys** [bitstarr/grav-plugin-twig-extensions#2]
After updating all plugins and core I got this message. I have been running this for a few years without a problem. I am not a coder, maybe someone can help me out?

`<span class="posted-on">
                    <i class="far fa-calendar"></i>
                    <time datetime='{{ page.date|date("c") }}'>
                    {{ page.date|localizeddate('medium', 'none', 'nl', 'Europe/Rome', 'd MMM yyyy') }}
                    </time>
                </span>`

![2023-11-25_16-24](https://github.com/bitstarr/grav-plugin-twig-extensions/assets/24695937/63be98dd-e19f-4d93-8b24-4959904956d1)

**Comment by pmoreno-rodriguez** [comment]
Hi. Same for me.
In this case, the problem seems to be related to the scope of the variable. The $customDateFormat variable is being used within a conditional block and might not be defined in all cases, which could be causing the error you mention.

To fix this, you can declare the $customDateFormat variable before the conditional block, initializing it with a default value, for example:
```
$intDateFormat = $dateFormat;
$customDateFormat = null;
    if  ( !array_key_exists( $dateFormat, $formatValues ) )
    {
        $intDateFormat = 'none';
        $customDateFormat = $dateFormat;
    }
```
With **$customDateFormat = null;** before the conditional block, seems it works fine.

**Comment by jooru** [comment]
While Author has not proposed an universal solution, try to change the order of the arguments in the formatting call, f. e.:

`{{ page.date|localizeddate('medium', 'none', 'nl', 'Europe/Rome', 'd MMM yyyy') }}`
↓
`{{ page.date|localizeddate('d MMM yyyy', 'none', 'nl', 'Europe/Rome') }}`

It worked for me now.

**Comment by Japhys** [comment]
Thanks both! @jooru worked for me as well!

**Comment by pmoreno-rodriguez** [comment]
@Japhys , in my opinion, this issue should be reopened, because the solution offered by @jooru is a partial, unofficial solution from the plugin author. Furthermore, setting 'd MMM yyyy' literally in the code does not give users the option to change the date format.

**Comment by Japhys** [comment]
Done

**Comment by bitstarr** [comment]
Hey folks,
i just saw your issues and will commit a fix right now. @pmoreno-rodriguez solution was correct. I just forgot to declare the variable before the conditions. Sorry for the inconvenience.
